Зоны ответственности
1. Управление промокодами: Создание, редактирование и удаление промокодов
2. Комментарии: Управление комментариями к промокодам
3. Интеграция со статистикой: Отправка событий (лайки, просмотры, комментарии) в сервис статистики через Kafka

Границы сервиса
1. Не отвечает за аутентификацию пользователей.
2. Не хранит статистику, только отправляет события для её сбора
