Зоны ответственности
1. Сбор статистики: Получает события от других сервисов
2. Хранение статистики: Сохраняет данные в аналитической базе данных
3. Предоставление статистики: Возвращает статистику по запросу через API

Границы сервиса
1. Не управляет промокодами или пользователями
2. Не обрабатывает бизнес-логику, связанную с созданием или редактированием промокодов
