Зоны ответственности
1. Регистрация и аутентификация: Управляет созданием аккаунтов и входом/ввыходом
2. Управление профилями: Хранит информацию о пользователях
3. Роли и права доступа: Управляет ролями пользователей

Границы сервиса
1. Не отвечает за бизнес-логику, связанную с промокодами или статистикой
2. Хранит данные только о пользователях и их ролях
